spring.application.name=gestiongarage
server.port=8383
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gestion_garage
spring.datasource.username=postgres
spring.datasource.password=P@sser-2024
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
app.security.bootstrap-admin.enabled=true
app.security.bootstrap-admin.username=admin
app.security.bootstrap-admin.password=admin123
app.security.jwt.secret=garagix-dev-secret-change-me-before-production
app.security.jwt.expiration-seconds=86400
# ===============================
# HikariCP settings
# ===============================
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=600000
